
spring:
  main:
    allow-bean-definition-overriding: true
  # 配置数据源
  datasource:
    url: jdbc:oracle:thin:@192.168.1.47:1521/orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: lyf
    password: lyf
#  datasource:
##    url: jdbc:mysql://localhost:3306/netfactory?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false
#    url: jdbc:mysql://47.102.197.84:3306/netfactory?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    password:

  # 配置redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

  # 配置thymeleaf
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  resources:
    static-locations: classpath:/static/

#配置mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/web/dao/*.xml

# 配置logback
logging:
  config: classpath:logback-spring.xml

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#端口号
server:
  port: 8080





